name: read label

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  read-label:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR label is `${{ toJson(github.event.pull_request.labels) }}`"
      - if: contains(github.event.pull_request.labels.*.name, 'frontend')
        run: echo "frontend contains"        
