name: trigger event

on: workflow_dispatch

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/OWNER/REPO/dispatches \
          -f "event_type=event" \
          -F "client_payload[pull_request]=안녕하세요"
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS }}
