name: trigger event

on: workflow_dispatch

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api /repos/heenahan/github-action/dispatches 
          -f event_type='event'
          -f context_payload='{ "pull_request": '${{ toJson(github.event.pull_request) }}' }'
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS }}
