name: trigger event

on: workflow_dispatch

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - run: gh api /repos/heenahan/github-action/dispatches -f event_type='event'
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS }}
