name: trigger event

on: workflow_dispatch

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
          --method POST \
          /repos/heenahan/github-action/dispatches \
          -f event_type='event' \
          -f client_payload='{ "pull_request": "안녕하세요" }'
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS }}
