name: trigger event

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_ACCESS }}
          repository: heenahan/github-action
          event-type: event
          client-payload: |-
            {
              "pull_request": ${{ toJson(github.event.pull_request) }},
              "review": ${{ toJson(github.event.review) }}
            }
