name: trigger event

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/heenahan/github-action/dispatches \
          -f "event_type=event" \
          -F "client_payload[pull_request][id]=${{ github.event.pull_request.id }}" \
          -F "client_payload[pull_request][assignees]=${{ toJson(github.event.pull_request.assignees) }}" \
          -F "client_payload[review][user]=${{ toJson(github.event.review.user) }}" \
          -F "client_payload[review][html_url]=${{ github.event.review_html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS }}
